### ISSUE TITLE
Good practices for production for docker

### ISSUE THREAD

**Issue by psychok7** [psychok7/django-yadpt-starter#5]
keep following https://docs.docker.com/compose/production/ and change `Removing any volume bindings for application code, so that code stays inside the container and can’t be changed from outside` for now

**Comment by psychok7** [comment]
for example:

```
  smal_web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/staging/Dockerfile
    command: /gunicorn.sh
    depends_on:
      - smal_postgis
      - smal_mongo
      - smal_redis

  smal_nginx:
    restart: always
    build: ./compose/nginx/staging
    depends_on:
      - smal_web
    volumes:
      - ./media:/code/media
      - ./staticfiles:/code/staticfiles
    ports:
      - "0.0.0.0:8008:80"

```
