### ISSUE TITLE
Resource usage and performance analyzer

### ISSUE THREAD

**Issue by psychok7** [psychok7/django-yadpt-starter#6]
Consider adding something like https://hub.docker.com/r/google/cadvisor/ for analyzing resource usage and performance

**Comment by psychok7** [comment]
```
  xxx_cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
```
